services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    buildCommand: ./render-build.sh
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: APP_KEY
        value: base64:PD/xgrdtdwzyX3iQesoqxy3BJzjJTDxD5CedcSbbkxQ=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://<to-be-generated>.onrender.com
      - key: DB_CONNECTION
        value: pgsql # or mysql
      - key: DB_HOST
        fromDatabase:
          name: your-database-name
          property: host
      - key: DB_PORT
        fromDatabase:
          name: your-database-name
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: your-database-name
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: your-database-name
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: your-database-name
          property: password

databases:
  - name: your-database-name
